// Mocks generated by Mockito 5.3.2 from annotations
// in desafio_flutter/test/modules/github/cubit/github_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:desafio_flutter/modules/github/domain/entities/github_container.dart'
    as _i6;
import 'package:desafio_flutter/modules/github/domain/errors/errors.dart'
    as _i5;
import 'package:desafio_flutter/modules/github/domain/usecases/fetch_github_repositories.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchGithubRepositoriesInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchGithubRepositoriesInterface extends _i1.Mock
    implements _i3.FetchGithubRepositoriesInterface {
  @override
  _i4.Future<
      _i2.Either<_i5.FailureGithubInterface?, _i6.GithubContainer?>> call(
    String? language,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            language,
            page,
          ],
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.FailureGithubInterface?,
                    _i6.GithubContainer?>>.value(
            _FakeEither_0<_i5.FailureGithubInterface?, _i6.GithubContainer?>(
          this,
          Invocation.method(
            #call,
            [
              language,
              page,
            ],
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.FailureGithubInterface?,
                    _i6.GithubContainer?>>.value(
            _FakeEither_0<_i5.FailureGithubInterface?, _i6.GithubContainer?>(
          this,
          Invocation.method(
            #call,
            [
              language,
              page,
            ],
          ),
        )),
      ) as _i4.Future<
          _i2.Either<_i5.FailureGithubInterface?, _i6.GithubContainer?>>);
}
